export const EXTERNAL_CONNECTION = "have a endpoint named {}";
export const EXTERNAL_OUTPUT = "connect to {} and save the output into {}";
export const PASS_OUTPUT = "pass the output to {}";
export const POST_AND_SAVE_TO_VARIABLE = "connect to {} and pass it the content of {} and save the output into {}";
export const PARALLEL_GET = "execute parallel GET to {} and save the result named {} within the object {}";
export const PARALLEL_GET_ARRAY = "execute parallel GET to array {} and save the result named {} within the object {}";
export const PARALLEL_POST = "execute parallel POST with {} to {} and save the result named {} within the object {}";
export const PARALLEL_POST_ARRAY_WITHIN = "execute parallel POST with {} to array {} and save the result named {} within the object {}";
export const PARALLEL_POST_ARRAY = "execute parallel POST with {} to array {} and save the result named {}";
