# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        node-version: [16.13.0, 18]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - uses: supercharge/redis-github-action@1.4.0
      with:
        redis-version: 6
    - run: yarn
    - run: yarn add -W zenroom@latest
    - run: yarn build
    - run: yarn test
    - uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage/lcov.info
  publish:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    needs: build
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: "0"
    - uses: actions/setup-node@v3
      with:
        node-version: 16.x
        registry-url: 'https://registry.npmjs.org'
    - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
    - run: yarn
    - run: yarn add -W zenroom@next
    - run: yarn build
    - run: git update-index --assume-unchanged package.json
    - name: Install lerna globally
      run: npm install --global --loglevel=error lerna
    - name: Authenticate with Registry and publish
      run: |
          yarn logout
          echo "//registry.npmjs.org/:_authToken=$NODE_AUTH_TOKEN" > .npmrc
          npm whoami
          lerna publish --no-verify-access -c -y --pre-dist-tag next --preid $(git rev-parse --short HEAD) --force-publish=*
      env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

